In [1]:
# Paired Student's t-test
import pandas as pd
from scipy.stats import ttest_rel
import numpy as np

def readRes(filename, cond=False):
    if cond:
        return pd.read_csv(filename, sep="\t", names=["fold","qid", "score"])
    return pd.read_csv(filename, sep="\t", names=["fold","qid", "score"])["score"].tolist()

In [17]:
# data1 = readRes("out5/epoch20/vanilla_bert_query_split_2020_01_25_15_40_45.rp")
# data1 = readRes("out5/vanilla_bert_query-wiki-question-ms-nostopword_split_2020_01_26_23_03_58.rp")
metricKeys = {"%s@%d" % (i, j): [] for i in ["p", "r", "ndcg", "nerr"] for j in [5, 10, 15, 20]}
metricKeys["rp"] = []

for key in metricKeys:
    data1 = readRes("out/february/vanilla_bert_query_all_e20_2020_02_02_17_32_14.%s" % key)
#     data2 = readRes("out/february/vanilla_bert_query-title-bm25-nostopword_all_e20_2020_02_02_17_35_41.%s" % key)
#     data2 = readRes("out/february/ms_m2_query_all_e50_2020_02_04_00_07_32.%s" % key)
#     data2 = readRes("out/february/vanilla_birch_m3_query_wikipedia3_all_e20_2020_02_04_01_18_17.%s" % key)
#     data2 = readRes("out/february/vanilla_birch_m1_query_wikipedia1_all_e20_2020_02_04_01_17_08.%s" % key)
#     data2 = readRes("out/february/vanilla_birch_m1_query_wikipedia3_all_e20_2020_02_04_01_17_07.%s" % key)
    data2 = readRes("out/february/vanilla_birch_m1_query_wikipedia5_all_e20_2020_02_04_01_17_06.%s" % key)
    print(key, ttest_rel(np.array(data1), np.array(data2)), np.mean(data1), np.mean(data2))

p@5 Ttest_relResult(statistic=-1.1766749646013632, pvalue=0.24007562356589623) 0.8443850267379679 0.8545454545454546
p@10 Ttest_relResult(statistic=-1.0519076567360048, pvalue=0.2935229017077021) 0.7802139037433156 0.7868983957219253
p@15 Ttest_relResult(statistic=-0.3858980955577613, pvalue=0.6997921453056439) 0.7218359866310162 0.7236185374331551
p@20 Ttest_relResult(statistic=-0.4617362747349673, pvalue=0.6445396247919761) 0.6599394064171124 0.6615436844919785
r@5 Ttest_relResult(statistic=-1.9217543867181808, pvalue=0.05539826946542154) 0.29180018181818185 0.298114871657754
r@10 Ttest_relResult(statistic=-1.0859624370553427, pvalue=0.27819693032593334) 0.514113973262032 0.5184127834224599
r@15 Ttest_relResult(statistic=-0.47467225389665973, pvalue=0.6352983828503054) 0.677581820855615 0.6795521497326203
r@20 Ttest_relResult(statistic=-0.4734069152070608, pvalue=0.6361998371904438) 0.7990385561497326 0.8009095213903744
ndcg@5 Ttest_relResult(statistic=-2.3769603382346536, pvalue=0.017959712184935087) 0.6018176336898396 0.6209996818181819
ndcg@10 Ttest_relResult(statistic=-2.45233541938944, pvalue=0.014650646052335977) 0.6543674037433155 0.670332243315508
ndcg@15 Ttest_relResult(statistic=-2.490509460954236, pvalue=0.013190339652085025) 0.6859804144385028 0.6989538422459892
ndcg@20 Ttest_relResult(statistic=-2.5481634733524774, pvalue=0.011229340435511312) 0.7247765347593582 0.7367002887700536
nerr@5 Ttest_relResult(statistic=-2.5415137550913265, pvalue=0.011441419471782855) 0.7129364518716578 0.7409835133689839
nerr@10 Ttest_relResult(statistic=-2.5839627764981774, pvalue=0.010146713407593091) 0.7238056176470589 0.7516304705882352
nerr@15 Ttest_relResult(statistic=-2.5864659405966086, pvalue=0.010074625288797628) 0.7246443556149732 0.7524329866310161
nerr@20 Ttest_relResult(statistic=-2.5904522671488026, pvalue=0.009960768861794879) 0.7247610561497327 0.7525872272727273
rp Ttest_relResult(statistic=-2.0546259886552813, pvalue=0.040611322396984194) 0.7295401764705882 0.7390187647058823

In [16]:
metricKeys = {"%s@%d" % (i, j): [] for i in ["p", "r", "ndcg", "nerr"] for j in [5, 10, 15, 20]}
metricKeys["rp"] = []
cond = True

for key in metricKeys:

#     data1 = readRes("out/january/vanilla_bert_query_split_e20_2020_01_28_21_50_05.%s" % key)
#     data2 = readRes("out/january/vanilla_bert_query-title-bm25-bert-nostopword_split_e20_2020_01_28_22_17_48.%s" % key)
#     data1 = readRes("out/january/vanilla_bert_query_all_e20_2020_01_28_21_49_46.%s" % key)
#     data2 = readRes("out/january/vanilla_bert_query-title-bm25-nostopword_all_e20_2020_01_28_22_36_19.%s" % key)
#     data2 = readRes("out/january/vanilla_bert_query-title-wiki-bm25-v2-nostopword_all_e20_2020_01_29_11_00_54.%s" % key)
#     data2 = readRes("out/january/vanilla_bert_query-title-bm25-bert-nostopword_all_e20_2020_01_28_22_12_30.%s" % key)
#     data2 = readRes("out/january/vanilla_bert_query-title-bm25-ms-nostopword_all_e20_2020_01_29_08_20_52.%s" % key, cond)



#     data1 = readRes("out/january/longQuery/vanilla_bert_query-title-bm25_all_e20_2020_01_29_15_38_50.%s" % key)
#     data2 = readRes("out/january/longQuery/vanilla_bert_query-title-bm25-nostopword_all_e20_2020_01_29_17_49_11.%s" % key, cond)
#     data2 = readRes("out/january/longQuery/vanilla_bert_query-title-bm25-bert-nostopword_all_e20_2020_01_29_14_04_41.%s" % key)
#     data2 = readRes("out/january/longQuery/vanilla_bert_query-title-overview-bm25-v2_all_e20_2020_01_29_15_38_50.%s" % key)
#     data2 = readRes("out/january/longQuery/vanilla_bert_query-title-bm25-nostopword_all_e20_2020_01_29_17_49_11.%s" % key)
#     data2 = readRes("out/january/longQuery/vanilla_bert_query-title-text-bm25-v2_all_e20_2020_01_29_16_09_49.%s" % key)
#     data2 = readRes("out/january/longQuery/cedr_knrm_query-title-bm25-tmp_all_e20_2020_01_29_20_46_34.%s" % key)
#     data2 = readRes("out/january/longQuery/vanilla_bert_query-title-bm25_all_e20_2020_01_30_11_18_05.%s" % key, cond)
    
#   tmp bm25
#     data2 = readRes("out/january/longQuery/vanilla_bert_query-title-overview-bm25-tmp_all_e20_2020_01_30_07_53_53.%s" % key)
#     data2 = readRes("out/january/longQuery/vanilla_bert_query-title-sectionLabel-bm25-tmp_all_e20_2020_01_30_07_53_53.%s" % key)
#     data2 = readRes("out/january/longQuery/vanilla_bert_query-title-overview-bm25_all_e20_2020_01_30_11_18_06.%s" % key)
#     data2 = readRes("out/january/longQuery/vanilla_bert_query-title-sectionLabel-bm25_all_e20_2020_01_30_11_18_05.%s" % key)

#   QQ and QW
    data2 = readRes("out/january/longQuery/vanilla_bert_query-qq-bm25-nostopword_all_e20_2020_01_30_16_34_16.%s" % key, cond)
#     data2 = readRes("out/january/longQuery/vanilla_bert_query-title-qq-bm25-nostopword_all_e20_2020_01_30_16_34_16.%s" % key)
#     data2 = readRes("out/january/longQuery/vanilla_bert_query-qw-bm25-nostopword_all_e20_2020_01_30_16_34_16.%s" % key)
#     data2 = readRes("out/january/longQuery/vanilla_bert_query-title-qw-bm25-nostopword_all_e20_2020_01_30_16_34_15.%s" % key, cond)
#     data2 = readRes("out/january/longQuery/.%s" % key)
#     data2 = readRes("out/january/longQuery/.%s" % key)
#     data2 = readRes("out/january/longQuery/.%s" % key)

# BIRCH
    data1 = readRes("out/february/vanilla_bert_query_all_e20_2020_02_02_11_09_36.%s" % key, cond)
#     data1 = readRes("out/january/longQuery/vanilla_bert_m1_query-type_all_e20_2020_02_02_10_06_34.%s" % key)
    
#     data2 = readRes("out/january/longQuery/vanilla_birch_m1_query_all_e20_2020_02_02_10_12_21.%s" % key)
#     data2 = readRes("out/february/vanilla_bert_query-title-bm25_all_e20_2020_02_02_14_12_52.%s" % key, cond)
    data2 = readRes("out/february/vanilla_birch_m3_query_wikipedia1-nostopword_all_e20_2020_02_02_22_10_56.%s" % key, cond)
    
#     goodQid = set([])
#     for f, q, i, j in zip(data1['fold'], data1['qid'], data1['score'], data2['score']):
#         if j > i:
#             goodQid.add((f,q))
#             print(f, q, df[df.query_id ==q].entityType.values[0])
    _, pval = ttest_rel(np.array(data1['score']), np.array(data2['score']))
    sig = "N"
    if pval < 0.01:
        sig = "* significant"
    elif pval < 0.05:
        sig = "significant"
    print(key, sig, pval, np.mean(data1['score']), np.mean(data2['score']))
    
#     for t in type2ids:
#         try:
#             d1 = data1[data1.qid.isin(type2ids[t])]['score'].values
#             d2 = data2[data2.qid.isin(type2ids[t])]['score'].values
#             if len(d1) == 0:
#                 continue
            
# #             d1 = data1[data1[data1.qid.isin([int(i) for i in type2ids[t]])]]['score']
# #             d2 = data2[data2[data2.qid.isin([int(i) for i in type2ids[t]])]]['score']
#             _, pval = ttest_rel(np.array(d1), np.array(d2))
#             sig = "N"
#             if pval < 0.01:
#                 sig = "* significant"
#                 print(key, t, sig, np.mean(d1), np.mean(d2))
                
#             elif pval < 0.05:
#                 sig = "significant"
#                 print(key, t, sig, np.mean(d1), np.mean(d2))
#         except:
#             continue

p@5 N 0.21529580363319742 0.8443850267379679 0.8550802139037432
p@10 N 0.0680352410869259 0.7802139037433156 0.7914438502673797
p@15 * significant 0.002482340729784975 0.7218359866310162 0.7348484812834224
p@20 significant 0.023948097983064513 0.6599394064171124 0.6672923475935828
r@5 N 0.24985790097179958 0.29180018181818185 0.29535174598930486
r@10 N 0.07041821820712427 0.514113973262032 0.5211070855614973
r@15 * significant 0.0019680331613130225 0.677581820855615 0.6897010481283422
r@20 significant 0.018572511573089187 0.7990385561497326 0.8079227245989304
ndcg@5 N 0.06827545105600792 0.6018176336898396 0.6165660294117647
ndcg@10 significant 0.04521088840107529 0.6543674037433155 0.6664152486631015
ndcg@15 * significant 0.0002521825543473776 0.6859804144385028 0.7032733128342247
ndcg@20 * significant 0.0006271519578000982 0.7247765347593582 0.7395255508021391
nerr@5 N 0.06501078729843472 0.7129364518716578 0.7329141631016043
nerr@10 N 0.06284960206195798 0.7238056176470589 0.7433669652406417
nerr@15 N 0.061529049849196285 0.7246443556149732 0.7442775855614974
nerr@20 N 0.061689365990060474 0.7247610561497327 0.744381179144385
rp significant 0.02286743827316261 0.7295401764705882 0.7397777192513368

In [110]:
type2ids[t]

array([183, 190, 204, 211, 227])

In [111]:
data1[data1.qid.isin(type2ids[t])]

     fold  qid     score
39      0  183  0.461538
129     1  204  0.851852
136     1  211  0.640000
152     1  227  0.833333
186     1  190  0.652174
271     2  204  0.851852
278     2  211  0.560000
294     2  227  0.833333
334     3  211  0.600000
372     4  227  0.791667

In [8]:
import json
df = pd.read_csv("data/AKG/Test Collection/AKGG/akg_standard_akgg_property_rele.csv")
df_action = pd.read_csv("data/AKG/Test Collection/AM/akg_standard_am_verb_object_rele.csv")

with open("data/AKG/Formal Run Topics/AKGG_Formal_Run_Topic.json") as json_file:
    data = json.load(json_file)
    qid, query, entity, entityType, action = [], [], [], [], []
    for p in data['queries']:
        qid.append(p['queryId'])
        query.append(p['query'])   
        entity.append(p['entity'])
        entityType.append(' '.join(p['entityTypes']))    
        action.append(p['action'])
topic = pd.DataFrame({"query_id": qid, "query": query, "entity": entity, "entityType": entityType, "action":action})
for c in ["query", "entityType", "action", "entity"]:
    topic[c] = topic[c].str.lower().replace("\'", "")
    
df = df.merge(topic, how="inner", on="query_id")
# df['query'] = df[['action', 'entity', 'entityType']].astype(str).apply(' '.join, axis=1)

In [9]:
type2ids = df.groupby("entityType")["query_id"].unique().to_dict()

In [15]:
df

,query_id,property,rele_label,query,entity,entityType,action
0,1,startTime,2,benchmarking,benchmarking,thing action,have
1,1,result,3,benchmarking,benchmarking,thing action,have
2,1,target,1,benchmarking,benchmarking,thing action,have
3,1,name,3,benchmarking,benchmarking,thing action,have
4,1,actionStatus,3,benchmarking,benchmarking,thing action,have
5,1,object,3,benchmarking,benchmarking,thing action,have
6,1,instrument,1,benchmarking,benchmarking,thing action,have
7,1,disambiguatingDescription,2,benchmarking,benchmarking,thing action,have
8,1,description,2,benchmarking,benchmarking,thing action,have
9,1,participant,2,benchmarking,benchmarking,thing action,have
10,1,agent,3,benchmarking,benchmarking,thing action,have
11,2,potentialAction,3,bodybuilding,bodybuilding,thing action,take
12,2,participant,3,bodybuilding,bodybuilding,thing action,take
13,2,startTime,3,bodybuilding,bodybuilding,thing action,take
14,2,endTime,2,bodybuilding,bodybuilding,thing action,take
15,2,instrument,2,bodybuilding,bodybuilding,thing action,take
16,2,result,2,bodybuilding,bodybuilding,thing action,take
17,2,additionalType,2,bodybuilding,bodybuilding,thing action,take
18,2,image,2,bodybuilding,bodybuilding,thing action,take
19,2,object,2,bodybuilding,bodybuilding,thing action,take
20,3,result,3,brainstorming,brainstorming,thing action,brainstorm
21,3,image,2,brainstorming,brainstorming,thing action,brainstorm
22,3,participant,2,brainstorming,brainstorming,thing action,brainstorm
23,3,description,1,brainstorming,brainstorming,thing action,brainstorm
24,3,potentialAction,2,brainstorming,brainstorming,thing action,brainstorm
25,3,location,2,brainstorming,brainstorming,thing action,brainstorm
26,3,startTime,1,brainstorming,brainstorming,thing action,brainstorm
27,3,target,1,brainstorming,brainstorming,thing action,brainstorm
28,3,endTime,1,brainstorming,brainstorming,thing action,brainstorm
29,3,alternateName,1,brainstorming,brainstorming,thing action,brainstorm
...,...,...,...,...,...,...,...
3766,227,weight,2,volkswagen passat,volkswagen passat,thing product vehicle car,remove the door panel
3767,227,review,2,volkswagen passat,volkswagen passat,thing product vehicle car,remove the door panel
3768,227,category,2,volkswagen passat,volkswagen passat,thing product vehicle car,remove the door panel
3769,227,name,2,volkswagen passat,volkswagen passat,thing product vehicle car,remove the door panel
3770,227,isConsumableFor,1,volkswagen passat,volkswagen passat,thing product vehicle car,remove the door panel
3771,228,isSimilarTo,4,apple cider,apple cider,thing product,drink
3772,228,productionDate,3,apple cider,apple cider,thing product,drink
3773,228,logo,2,apple cider,apple cider,thing product,drink
3774,228,purchaseDate,2,apple cider,apple cider,thing product,drink
3775,228,color,1,apple cider,apple cider,thing product,drink
3776,228,name,2,apple cider,apple cider,thing product,drink
3777,228,brand,3,apple cider,apple cider,thing product,drink
3778,228,isRelatedTo,2,apple cider,apple cider,thing product,drink
3779,228,isAccessoryOrSparePartFor,4,apple cider,apple cider,thing product,drink
3780,228,material,2,apple cider,apple cider,thing product,drink
3781,228,category,2,apple cider,apple cider,thing product,drink
3782,228,isConsumableFor,2,apple cider,apple cider,thing product,drink
3783,228,manufacturer,4,apple cider,apple cider,thing product,drink
3784,228,weight,2,apple cider,apple cider,thing product,drink
3785,228,productID,4,apple cider,apple cider,thing product,drink
3786,228,alternateName,2,apple cider,apple cider,thing product,drink
3787,228,itemCondition,2,apple cider,apple cider,thing product,drink
3788,228,review,1,apple cider,apple cider,thing product,drink
3789,228,model,2,apple cider,apple cider,thing product,drink
3790,228,additionalProperty,2,apple cider,apple cider,thing product,drink
3791,229,potentialAction,4,labrador retriever,labrador retriever,thing,keep
3792,229,url,4,labrador retriever,labrador retriever,thing,keep
3793,229,description,3,labrador retriever,labrador retriever,thing,keep
3794,229,name,2,labrador retriever,labrador retriever,thing,keep
3795,229,alternateName,2,labrador retriever,labrador retriever,thing,keep